Update GH templates
ObolNetwork/charon-k8s-distributed-validator-cluster pull request #72
Opened 2023-02-07 11:29 UTC by thomasheremans

2023-02-07 12:09 UTC, LukeHackett12 requested changes

2023-02-07 12:09 UTC, LukeHackett12 commented on .github/ISSUE_TEMPLATE/feature_request.md
> +- [ ] Has a attested on a testnet at least once
```suggestion
- [ ] Has attested on a testnet at least once
```

2023-02-07 12:09 UTC, LukeHackett12 commented on .github/ISSUE_TEMPLATE/feature_request.md
> +- [ ] Approved design doc: *link*
```suggestion
- [ ] Approved design doc: [link](*url*)
```

2023-02-07 12:33 UTC, dB2510 commented on .github/pull_request_template.md
> +🧑‍🎓 Please review our contribution guide https://github.com/ObolNetwork/charon/blob/main/docs/contributing.md
charon's contribution guide

2023-02-07 12:49 UTC, thomasheremans commented on .github/pull_request_template.md
> +🧑‍🎓 Please review our contribution guide https://github.com/ObolNetwork/charon/blob/main/docs/contributing.md
Isn't it the same for these repos?

2023-02-15 03:49 UTC, eth2devops approved these changes
LGTM

2023-02-17 13:05 UTC, LukeHackett12 approved these changes

2023-02-17 13:05 UTC, merged