Add nimbus template for testing
ObolNetwork/charon-k8s-distributed-validator-cluster pull request #87
Opened 2023-03-09 19:33 UTC by LukeHackett12

Add nimbus yaml testing template

category: feature

ticket: #000

2023-03-09 20:06 UTC, eth2devops requested changes

2023-03-09 20:06 UTC, eth2devops commented on templates/nimbus-vs.yaml
> +            volume_mount:
we no longer need the cluster-lock and the private-key volumes

2023-03-10 15:28 UTC, eth2devops submitted a review, later dismissed

2023-03-10 15:30 UTC, dB2510 submitted a review, later dismissed

2023-03-10 15:30 UTC, dB2510 commented on templates/nimbus-vs.yaml
> +---
filename should be `nimbus-vc.yaml`.

2023-03-10 19:40 UTC, eth2devops approved these changes

2023-03-10 19:40 UTC, merged